Add dummy plays
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

diff --git a/dummy b/dummy
--- a/dummy
+++ b/dummy
@@ -7,6 +7,37 @@
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 LL="dummy"
+# pop an action to play from a text file (from the last file line)
+# $1 - the file name like /tmp/dummy_plays_monitor
+# $2 - the comment message for the action to be played eg. "action monitor"
+# $3 - default action, if there is no action to play from the file
+# allowed actions to play: ERROR, FAILED_MASTER, RUNNING_MASTER, SUCCESS, NOT_RUNNING
+dummy_pop() {
+    local LH="${LL} dummy_pop():"
+    local action
+    local default_action
+    default_action="${3:-SUCCESS}"
+    if [ -f $1 ] ; then
+        action="$(tail -1 $1)"
+        sed -i '$ d' $1
+    fi
+    action="${action:-$default_action}"
+    ocf_log info "${LH} dummy plays ${action} for the $2"
+    case "${action}" in
+        "ERROR")
+            exit $OCF_ERR_GENERIC ;;
+        "FAILED_MASTER")
+            exit $OCF_FAILED_MASTER ;;
+        "RUNNING_MASTER")
+            exit $OCF_RUNNING_MASTER ;;
+        "SUCCESS")
+            exit $OCF_SUCCESS ;;
+        "NOT_RUNNING")
+            exit $OCF_NOT_RUNNING ;;
+        *) ;;
+    esac
+    exit $OCF_SUCCESS
+}
 meta_data() {
 cat <<END
 <?xml version="1.0"?>
@@ -18,23 +49,19 @@ END
 }
 action_status() {
     local LH="${LL} action_status():"
-    ocf_log info "${LH} I'm OK"
-    return $OCF_SUCCESS
+    dummy_pop "/tmp/dummy_plays_status" "status"
 }
 action_monitor() {
     local LH="${LL} action_monitor():"
-    ocf_log info "${LH} It's OK"
-    return $OCF_SUCCESS
+    dummy_pop "/tmp/dummy_plays_monitor" "monitor"
 }
 action_start() {
     local LH="${LL} action_start():"
-    ocf_log info "${LH} Started"
-    return $OCF_SUCCESS
+    dummy_pop "/tmp/dummy_plays_start" "start"
 }
 action_stop() {
     local LH="${LL} action_stop():"
-    ocf_log info "${LH} Stopped"
-    return $OCF_SUCCESS
+    dummy_pop "/tmp/dummy_plays_stop" "stop"
 }
 action_notify() {
     local LH="${LL} action_notify():"
@@ -43,46 +70,34 @@ action_notify() {
         # PRE- anything notify section
         case "$OCF_RESKEY_CRM_meta_notify_operation" in
             promote)
-                ocf_log info "${LH} pre-promote for '${OCF_RESKEY_CRM_meta_notify_promote_uname}' OK"
-                return $OCF_SUCCESS
-                #return $OCF_NOT_RUNNING
-                #return $OCF_ERR_GENERIC
-                #exit $OCF_FAILED_MASTER
+                dummy_pop "/tmp/dummy_plays_pre_promote" "pre-promote for '${OCF_RESKEY_CRM_meta_notify_promote_uname}'"
                 ;;
-            *)
+            start)
+                dummy_pop "/tmp/dummy_plays_pre_start" "pre-start for '${OCF_RESKEY_CRM_meta_notify_start_uname}'"
                 ;;
+            stop)
+                dummy_pop "/tmp/dummy_plays_pre_stop" "pre-stop for '${OCF_RESKEY_CRM_meta_notify_stop_uname}'"
+                ;;
+            demote)
+                dummy_pop "/tmp/dummy_plays_pre_demote" "pre-demote for '${OCF_RESKEY_CRM_meta_notify_demote_uname}'"
+                ;;
+            *)  ;;
         esac
     fi
     if [ "${OCF_RESKEY_CRM_meta_notify_type}" = 'post' ] ; then
         # POST- anything notify section
         case "$OCF_RESKEY_CRM_meta_notify_operation" in
             promote)
-                ocf_log info "${LH} post-promote for '${OCF_RESKEY_CRM_meta_notify_promote_uname}' ERROR"
-                #return $OCF_SUCCESS
-                #return $OCF_NOT_RUNNING
-                return $OCF_ERR_GENERIC
-                #exit $OCF_FAILED_MASTER
+                dummy_pop "/tmp/dummy_plays_post_promote" "post-promote for '${OCF_RESKEY_CRM_meta_notify_promote_uname}'" "ERROR"
                 ;;
             start)
-                ocf_log info "${LH} post-start for '${OCF_RESKEY_CRM_meta_notify_start_uname}' ERROR"
-                #return $OCF_SUCCESS
-                #return $OCF_NOT_RUNNING
-                return $OCF_ERR_GENERIC
-                #exit $OCF_FAILED_MASTER
+                dummy_pop "/tmp/dummy_plays_post_start" "post-start for '${OCF_RESKEY_CRM_meta_notify_start_uname}'" "ERROR"
                 ;;
             stop)
-                ocf_log info "${LH} post-stop for '${OCF_RESKEY_CRM_meta_notify_stop_uname}' ERROR"
-                #return $OCF_SUCCESS
-                #return $OCF_NOT_RUNNING
-                return $OCF_ERR_GENERIC
-                #exit $OCF_FAILED_MASTER
+                dummy_pop "/tmp/dummy_plays_post_stop" "post-stop for '${OCF_RESKEY_CRM_meta_notify_stop_uname}'" "ERROR"
                 ;;
             demote)
-                ocf_log info "${LH} post-demote for for '${OCF_RESKEY_CRM_meta_notify_demote_uname}' FAILED MASTER"
-                #return $OCF_SUCCESS
-                #return $OCF_NOT_RUNNING
-                #return $OCF_ERR_GENERIC
-                exit $OCF_FAILED_MASTER
+                dummy_pop "/tmp/dummy_plays_post_demote" "post-demote for '${OCF_RESKEY_CRM_meta_notify_demote_uname}'" "FAILED_MASTER"
                 ;;
             *)  ;;
         esac
@@ -91,19 +106,11 @@ action_notify() {
 }
 action_promote() {
     local LH="${LL} action_promote():"
-    ocf_log info "${LH} FAILED MASTER"
-    #return $OCF_SUCCESS
-    #return $OCF_NOT_RUNNING
-    #return $OCF_ERR_GENERIC
-    exit $OCF_FAILED_MASTER
+    dummy_pop "/tmp/dummy_plays_promote" "promote" "FAILED_MASTER"
 }
 action_demote() {
     local LH="${LL} action_demote():"
-    ocf_log info "${LH} FAILED MASTER"
-    #return $OCF_SUCCESS
-    #return $OCF_NOT_RUNNING
-    #return $OCF_ERR_GENERIC
-    exit $OCF_FAILED_MASTER
+    dummy_pop "/tmp/dummy_plays_demote" "demote" "FAILED_MASTER"
 }
 #######################################################################
 case "$1" in
@@ -125,3 +132,4 @@ case "$1" in
   validate-all) echo action_validate;;
   *)            usage;;
 esac
+
